---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs1
  labels:
    app: nodejs1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs1
  template:
    metadata:
      labels:
        app: nodejs1
    spec:
      containers:
      - name: nodejs
        image: gcr.io/helpful-lens-307104/nodejs-test
        ports:
        - containerPort: 80
        env:
        - name: MESSAGE
          value: "I'm backend 1"
      imagePullSecrets:
      - name: gcr-io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs2
  labels:
    app: nodejs2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs2
  template:
    metadata:
      labels:
        app: nodejs2
    spec:
      containers:
      - name: nodejs
        image: gcr.io/helpful-lens-307104/nodejs-test
        ports:
        - containerPort: 80
        env:
        - name: MESSAGE
          value: "I'm backend 2"
      imagePullSecrets:
      - name: gcr-io
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs1
spec:
  type: NodePort
  selector:
    app: nodejs1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80    
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs2
spec:
  type: NodePort
  selector:
    app: nodejs2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80    
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nodejs
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: nodejs1
          servicePort: 80
      - path: /2
        pathType: Prefix
        backend:
          serviceName: nodejs2
          servicePort: 80
